const FirstNames = [
	"Bibble",
	"Grizzle",
	"Zibble",
	"Muck",
	"Snorkle",
	"Dimple",
	"Fizz",
	"Tonk",
	"Wobble",
	"Crinkle",
	"Fumble",
	"Guzzle",
	"Jibble",
	"Krum",
	"Lumpy",
	"Mingle",
	"Nuggle",
	"Pibble",
	"Quibble",
	"Rumble",
	"Snaggle",
	"Tibble",
	"Wiggle",
	"Yibble",
	"Zonk",
	"Boggle",
	"Dazzle",
	"Flob",
	"Gurgle",
	"Hobble",
	"Juggle",
	"Kibble",
	"Muddle",
	"Pibble",
	"Squibble",
	"Tuzzle",
	"Wob",
	"Yaffle",
	"Zizzle",
	"Clonkle",
];

const LastNames = [
	"Fizzlewhip",
	"Mugwort",
	"Twiddlestump",
	"Puddlefoot",
	"Crumplethatch",
	"Froggleton",
	"Whirligig",
	"Knockersham",
	"Giggleplume",
	"Snagglebranch",
	"Wifflepuff",
	"Cobblepot",
	"Jabberloop",
	"Muckraker",
	"Snoggleton",
	"Blunderbelt",
	"Cragglehorn",
	"Frizzletoe",
	"Hufflebop",
	"Tumbletrunk",
	"Quirklehorn",
	"Dizzleshank",
	"Gobblefoot",
	"Waddlewink",
	"Mugglehop",
	"Jinglepatch",
	"Snickerfluff",
	"Wrigglebottom",
	"Squishmire",
	"Hobblekin",
	"Snortlewhack",
	"Grumbleplume",
	"Twaddlefoot",
	"Fizzlebranch",
	"Wigglespout",
	"Blunderwhip",
	"Squigglehorn",
	"Mubblethatch",
	"Knobbleroot",
	"Flapstumble",
];

const Monikors = [
	"the Unkempt",
	"the Sneezy",
	"the Jolly",
	"the Moist",
	"the Whisperer",
	"the Slightly Annoyed",
	"the Daring",
	"the Unlucky",
	"the Floppy",
	"the Tardy",
	"the Perplexed",
	"the Witty",
	"the Forgetful",
	"the Bizarre",
	"the Smelly",
	"the Eccentric",
	"the Chaotic",
	"the Bumbling",
	"the Brave(ish)",
	"the Distracted",
	"the Overcautious",
	"the Underprepared",
	"the Loud",
	"the Sleepy",
	"the Sticky",
	"the Squishy",
	"the Clumsy",
	"the Fickle",
	"the Persistent",
	"the Wobbly",
	"the Puzzled",
	"the Paranoid",
	"the Thirsty",
	"the Greedy",
	"the Hungry",
	"the Cautious",
	"the Happy-Go-Lucky",
	"the Unstoppable(ish)",
	"the Reluctant",
	"the Noisy",
];

export { FirstNames, LastNames, Monikors };
